### ISSUE TITLE
Possible bug in data encoding

### ISSUE THREAD

**Issue by silviucpp** [Alex-Zhuk/esmpp_lib#1]
Hello,
```
esmpp_lib_worker:submit(Pid, [{source_addr, <<"375296660002">>}, {dest_addr, <<"375296543210">>}, {text, <<"{}">>}]).
```
It's actually sending () instead {}.

**Comment by Alex-Zhuk** [comment]
Hello. What is the value of parameter "data_coding" is configured on the side of the operator on the channel smpp?

**Comment by silviucpp** [comment]
Hello Alex, 

I only tried to send a message with the default settings from your example. And I saw this problem in wireshark. I used as gateway a simulator: https://github.com/PowerMeMobile/smppsink

In your library I saw the function esmpp_lib_latin1_to_gsm:latin1_to_gsm(<<"{}">>, <<>>). is called.

And this one converts the { in (.

I noticed this because the simulator if receives : "submit:{status:1,delay:1}" it suppose to simulate an error but in case I use esmpp_lib is not working as time he receives : "submit:(status:1,delay:1)".

Using smppload is working fine. 

Is this helps you ?

Silviu

**Comment by silviucpp** [comment]
So in logs I can see : {data_coding,0}

**Comment by Alex-Zhuk** [comment]
The default library connects to the provider with the coding gsm (parameter {data_coding, 0}). To solve the problem, try to open a session with the latin1 encoding. To do this set parameter {data_coding, 3}. Example:

{ok, Pid} = esmpp_lib_worker:start_link([**{data_coding, 3}**, {host, {127,0,0,1}}, 
                    {port, 2775}, {password, <<"password">>}, 
                    {system_id, <<"smppclient1">>}, {interface_version, "3.4"}, 
                    {enquire_timeout, 30}, {submit_timeout, 60}, 
                    {system_type, ""}, {service_type, ""}, {addr_ton, 5}, 
                    {addr_npi, 0}, {source_addr_ton, 5}, {source_addr_npi, 0}, 
                    {dest_addr_ton, 1}, {dest_addr_npi, 1}, {handler, my_sms}, 
                    {mode, transceiver}]).

It usually helps with the real operators.

**Comment by silviucpp** [comment]
@this fixed my problem. Thanks a lot I'm closing the bug.

**Comment by silviucpp** [comment]
@maybe it's ok to put this also in documentation.

**Comment by Alex-Zhuk** [comment]
Add to Readme information about data_coding parameter.
