### ISSUE TITLE
Proposal for several improvements

### ISSUE THREAD

**Issue by silviucpp** [Alex-Zhuk/esmpp_lib#3]
Hello,

There are few changes that I might do over the project:

1.in `esmpp_lib_submit_processing` I will probably use a record as state to avoid
all the calls to `proplists:get_value` for `submit_check`, `worker_pid` and `submit_tref` (also will increase the readability over the code)

Something like:

`-record(state, {submit_check, worker_pid, submit_tref, options}).`

2.I will probably drop all calls to `proplists` module because it's slow. instead you can use the `lists:keyfind` which is much faster. 

You can create something like:
```
lookup(Key, List, Default) ->
    case lists:keyfind(Key, 1, List) of
        {Key, Result} ->
            Result;
        false ->
            Default
    end.

lookup(Key, List) ->
    lookup(Key, List, undefined).
```

in a separate module which emulates the `proplists` behaviour but with better performances.

3.In regards to my previous email I will add a way to make the link between request and response. The best way here I see to add a a new parameter called `user_info`. So when you send an sms 
you can do :

```
esmpp_lib_worker:submit(Pid, [{source_addr, <<"375296660002">>}, {dest_addr, <<"375296543210">>}, {text, <<"message here">>}, {user_info, UserInfo}]).
```

And in all callbacks regarding that sms you will pass this user info. This will let the app to make the link between the request and the response. 

4.When sending a large message that's going to be split in multiple pieces will be nice if we can get on the callbacks from what original message is part of and what's the order number. 

Let me know in case sounds ok for you and I can start coding myself and make some pull requests in regards to this

Silviu

**Comment by Alex-Zhuk** [comment]
I will try to answer this question tomorrow.

**Comment by Alex-Zhuk** [comment]
1. It is a good idea. It can be done.

2. Proplists in this case are very short and they have almost no effect on performance. Here, I would not change anything. I tested the library with loads that are unattainable in the real situation, no problems were observed

3. This version of the library describes smpp protocol. For integration into systems with a large number of gateways and many of channels on each gateway, natural need for more options in submit function. For example, in our complex I convay the message id from the database and the pid of the process, which works with a database.

4. I do not quite understand the question, please describe with an example.

You can make changes in your fork as you need.

**Comment by silviucpp** [comment]
For 4 : when you send a message that's going to be delivered in 4 messages will be nice to know this somehow on the process that called esmpp_lib_worker:submit.

**Comment by Alex-Zhuk** [comment]
4. You can store an identifier of a long text from database with the message_id of each SMS in which he was sent. If one of the sms is delivered unsuccessfull  you mark long message in the database as undeliverable.
