### ISSUE TITLE
Possible decoding error

### ISSUE THREAD

**Issue by silviucpp** [Alex-Zhuk/esmpp_lib#4]
```erl
 1281 ->
     {Value, Tail} = parse_integer_tag(Rest),
     {Tail, [{ussd_service_op, Value}]};
```

I think correct is : ` {Tail, [{ussd_service_op, Value} | List]};`

Same for `source_network_id`

Silviu

**Comment by Alex-Zhuk** [comment]
Thank You! This bug is fixed.

**Comment by silviucpp** [comment]
Also looking to the protocol specs and how you decode alert_on_message_delivery I'm not sure it's ok. 

I think should be:

```erl
 {Value, Tail} = parse_integer_tag(Rest),
{Tail, [{alert_on_message_delivery, Value}|List]};
```

Also on message_state I think you can simplify by:

```erl
{Value, Tail} = parse_integer_tag(Rest),
{Tail, [{message_state, Value}|List]};
```

Silviu

**Comment by Alex-Zhuk** [comment]
Hello. Bug in parameter alert_on_message_delivery is fixed. But 

 {Value, Tail} = parse_integer_tag(Rest),
{Tail, [{alert_on_message_delivery, Value}|List]};

is not right. alert_on_message_delivery has not value.

**Comment by Alex-Zhuk** [comment]
message_state

I didn't investigate why, but 

{Value, Tail} = parse_integer_tag(Rest),
{Tail, [{message_state, Value}|List]};

didn't work in my tests.

**Comment by silviucpp** [comment]
Hello,

Looking here: http://opensmpp.org/specs/smppv50.pdf

Regarding `alert_on_message_delivery` you are right I missed read the specs. But now I believe the initial implementation was the right one. Because from what I understand the value can be present or not. In case is not means the value is the default one (0). 

Regarding message state for me is working that implementation I provided.. and looking to the specs I don't see why is not working for you as well.

Silviu

**Comment by Alex-Zhuk** [comment]
Fixed.
