### ISSUE TITLE
Sequence numbers start at 0, but should start at 1

### ISSUE THREAD

**Issue by bwachter** [Alex-Zhuk/esmpp_lib#6]
I'm currently evaluating some smpp libraries, and was trying to figure out why this one can't get past the login with the smpp server I have here. Turns out, 0 is not a valid sequence number, and the server is rather strict about that, and refuses to continue. (http://docs.nimta.com/SMPP_v3_4_Issue1_2.pdf page 115)

**Comment by Alex-Zhuk** [comment]
Fixed.
